name: Daily Commit

# Trigger this workflow at 2:30 PM UTC every day
on:
  schedule:
    - cron: '25 18 * * *'

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Git configuration
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "23f2005217@ds.study.iitm.ac.in"  # Change this if needed

    # Step 3: Add changes (ensure you have something to commit)
    - name: Make changes or ensure files are updated
      run: |
        # Example: touch a file to ensure changes are detected
        echo "Automated update at $(date)" >> daily_log.txt
        git add .

    # Step 4: Commit the changes with your email in the message
    - name: Commit changes
      run: |
        git commit -m "Automated commit by 23f2005217@ds.study.iitm.ac.in"

    # Step 5: Push the changes back to the repository
    - name: Push changes
      run: |
        git push origin main  # Ensure you are pushing to the correct branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token to authenticate the push
